vMTS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vMTS.Models;

namespace vMTS.Controllers
{
    
    public class HomeController : Controller
    {
        GeneralModel g = new GeneralModel();

        public ActionResult Index()
        {
            ViewBag.title = "volunteer motorcycle training services - vMTS";

            ViewBag.description = "Volunteer Motorcycle Training Services is a Hendersonville, TN based organization that offers courses in motorcycle riding for people in Middle Tennessee.";

            g.GetCarouselImages = g.GetAllImages();
			var compnay = g.GetCompanyInfo();
			ViewBag.Telephone = compnay.Telephone;

            return View(g);
        }

        public ActionResult courses()
        {
            ViewBag.title = "Rider Courses";
            ViewBag.description = "Rider Courses for Volunteer Motorcycle Training Services in Hendersonville, TN offer the best training in motorcycle riding for people in Middle Tennessee.";

            return View(g.GetCourseDescriptions());
        }

        public ActionResult about()
        {
            ViewBag.title = "About vMTS";
            ViewBag.description = "About Volunteer Motorcycle Training Services in Nashville/Hendersonville, TN";

            return View();
        }


        public ActionResult fees()
        {
            ViewBag.title = "Course Fees";

            ViewBag.description = "Volunteer Motorcycle Training Services in Hendersonville, TN has the cheapest fees in middle tennessee";

            return View(g.GetCourseDescriptions());
        }

        public ActionResult contact()
        {
			GeneralModel general = new GeneralModel();
			var compnay = general.GetCompanyInfo();
            ViewBag.title = "Contact Us for More Information";
            ViewBag.description = "Contact Volunteer Motorcycle Training Services in Hendersonville, TN for More Information about motorcycle training courses";

            return View(compnay);
        }

        public ActionResult instructors()
        {
            ViewBag.title = "Experienced Rider Coaches";
            ViewBag.description = "vMTS offers the best motorcycle training in Hendersonville and middle TN";

            return View(g.GetAllInstructors());
        }

        public ActionResult sponsors()
        {
            ViewBag.title = "Sponsors";
            ViewBag.description = "Volunteer Motorcycle Training Services in Hendersonville, TN would like to thank our motocycle sponsors";

            return View(g.GetAllSponsors());
        }
        public ActionResult _location()
        {
            ViewBag.title = "Location";
            ViewBag.description = "Course Location Hendersonville, TN 37075";

            return View();
        }

        public ActionResult _media()
        {

            return View();
        }

        public ActionResult Error()
        {
            return View();
        }
    }
}

vMTS/Controllers/RegistrationController.cs
using DocumentFormat.OpenXml.ExtendedProperties;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using vMTS.Models;

namespace vMTS.Controllers
{
    //[RequireHttps]
    public class RegistrationController : Controller
    {
               RegistrationModel c = new RegistrationModel();
               RaceLookup Race = new RaceLookup();
               StateList States = new StateList();
               NameSuffix Suffix = new NameSuffix();
               CustomErrors CE = new CustomErrors();
               CommunicationModel CM = new CommunicationModel();
               AddressValidation AV = new AddressValidation();
        GeneralModel GM = new GeneralModel();

        // GET: Registration
        public ActionResult Index()
        {             
            string error ="";
            List <Class_Schedule_view> list = new List<Class_Schedule_view>();
			var company = GM.GetCompanyInfo();

			try
            {
				using (vmts_dataDataContext db = new vmts_dataDataContext())
                {
                    var sql = from c in db.Class_Schedule_views
                              where c.CLASS_START_DATE >= DateTime.Now// && c.OPEN_SEATS >= 1
                              orderby c.CLASS_START_DATE
                              group c by c.CLASS_TYPE into newGroup
                              select newGroup.ToList();

                    foreach (var e in sql)
                    {
                        foreach (var cg in e)
                            list.Add(new Class_Schedule_view
                            {
                                CLASS_ID = cg.CLASS_ID,
                                CLASS_TYPE = cg.CLASS_TYPE,
                                ClassDay = cg.ClassDay,
                                OPEN_SEATS = cg.OPEN_SEATS,
                                //CLASS_DESCRIPTION = cg.CLASS_DESCRIPTION,
                                CLASS_FEE = cg.CLASS_FEE,
                                CLASS_START_DATE = cg.CLASS_START_DATE,
                                CLASS_START_TIME = cg.CLASS_START_TIME,
                                CLASS_END_TIME = cg.CLASS_END_TIME,
                                C1 = cg.C1,
                                C2 = cg.C2
                                //,COURSE_NUMBER = e.COURSE_NUMBER
                            });
                    }
                }

				//List<InstructorClasses> ic = new List<InstructorClasses>();
				//ic = GM.GetInstructorClass();

				//foreach(var i in ic)-
				//{
				//    string clDay = list.IndexOf(i.ClassDates.ToString());
				//}
				

			}
            catch (Exception e)
            {
                error = e.Message;
            }

            var classesGrouped = from c in list
                                 group c by c.CLASS_TYPE into ct
                                 select new Group<string, Class_Schedule_view> { Key = ct.Key, Values = ct };

            var tuple = new Tuple<List<Group<string,Class_Schedule_view>>, List<CourseDescriptions>, List<InstructorClasses>>(classesGrouped.ToList(), GM.GetCourseDescriptions(),GM.GetInstructorClass());

			ViewBag.Email = company.Email;
			ViewBag.Telephone = company.Telephone;
			ViewBag.Owner = company.OwnerName;
			return View(tuple);
        }

        public ActionResult Register(Int32 id)
        {
            c.NameSuffix = Suffix.SuffixSelectList(); 
            c.RaceCodes = Race.RaceSelectList();
            c.States = States.StateSelectList();
			var company = GM.GetCompanyInfo();

           string Class = "";
            string ClassType = "";
           DateTime? Start;
            using (vmts_dataDataContext db = new vmts_dataDataContext())
            {
            var sql = (from cl in db.Class_Schedule_views
                       where cl.CLASS_ID==id
                       select (cl)).FirstOrDefault();
                ClassType = sql.CLASS_TYPE;
                Class = "(" + sql.ClassDay + ")";
                Start = sql.CLASS_START_DATE;
            }


            ViewBag.ClassRegistration = ClassType;
            ViewBag.ClassId = id;
            ViewBag.StartDate = String.Format("{0:d}",Start);
            ViewBag.Title = ClassType + Class;
			ViewBag.Email = company.Email;
			ViewBag.Telephone = company.Telephone;
			ViewBag.Owner = company.OwnerName;

            return View(c);
        }
        
        public ActionResult RegistrationConfirmation(Int64 id)
        {
            c.Confirmation = c.GetConfirmation(id);
            try { 
            c.RegistrationPayment = c.GetRegistrationPayment(id);

            ViewBag.ClassRegistration = c.GetConfirmation(id).FirstOrDefault().CLASS_DAY;
            ViewBag.ClassId = c.GetConfirmation(id).FirstOrDefault().CLASS_ID;
            ViewBag.Title = "Course Registration " + c.GetConfirmation(id).FirstOrDefault().CLASS_DAY;
            ViewBag.RegNum = id;


            }
            catch
            {
                CE.BadRequest();
            }
            return View(c);
        }

        public ActionResult PrintRegistration(Int64 id)
        {
            c.Confirmation = c.GetConfirmation(id);
            var p = c.GetConfirmation(id).FirstOrDefault().RECEIPT;
            c.RegistrationPayment = c.GetRegistrationPayment(p);

            ViewBag.ClassRegistration = c.GetConfirmation(id).FirstOrDefault().CLASS_DAY;
            ViewBag.ClassId = c.GetConfirmation(id).FirstOrDefault().CLASS_ID;
            ViewBag.Title = "vMTS Registration " + c.GetConfirmation(id).FirstOrDefault().CLASS_DAY;
            return View(c);
        }

        public ActionResult _RegistrationPayment(Int64 id)
        {
            var p = c.GetConfirmation(id).FirstOrDefault().RECEIPT;
            c.RegistrationPayment = c.GetRegistrationPayment(p);
            
            return View(c);
        }

        public ActionResult RegistrationEmailConfirmation(string id) 
        {
            if(string.IsNullOrEmpty(id))
            {
                ViewBag.HtmlStr = "";
                return View();
            }
            else
            {
                var confirmId = Guid.Parse(id);
                using (vmts_dataDataContext db = new vmts_dataDataContext())
                {
                    db.UpdateRegistrationEmailConfirm(confirmId, true);
                    var data = CM.SendClassDetials(confirmId);
                    ViewBag.HtmlStr = data;
                    return View();
                }
            }
            
        }

        public string NewClassRegistration(Int32 COURSE_ID, string FirstName, string MiddleName, string LastName, string Suffix, string Address1, string Address2, string City, string inputState, string Zip, string Gender, Int32? inputRace, string Phone, string Email, DateTime DOB, Int32 AGE, string Eval, string MOTOR_YR, string MOTOR_MK, string MOTOR_MD, string DL_NUM, string inputDLState, string PaymentType, string CardName, string CardNum, string CardMonth, string CardYear, string CardCVV, string PromoCode)
        {
            string msg = "";
            using (vmts_dataDataContext db = new vmts_dataDataContext())
            {
                try
                {
                    if(VerifyClassOpenings(COURSE_ID) > 0)
                    {

                    Int64? OrderNum = 0;
                        
                        inputRace = 8; // Set to empty Race
                        db.NewRegistration(COURSE_ID, FirstName, MiddleName, LastName, Suffix, Address1, Address2, City, inputState, Zip, Gender, inputRace, Phone, Email, DOB, AGE, Eval, MOTOR_YR, MOTOR_MK, MOTOR_MD, DL_NUM, inputDLState, PaymentType, CardName, CardNum, CardMonth, CardYear, CardCVV, PromoCode, GM.GetPromoCodeValue(PromoCode), ref OrderNum);

                    if (OrderNum.Value > 0)
                    {
                        msg = OrderNum.ToString();

                        CM.SendRegistrationMessage(OrderNum.Value);

                    }
                    }
                    else
                    {
                        msg = "Looks like this class is full, we apologize for the inconvience.  Please select another class date.";
                    }
                }
                catch (Exception e)
                {
                    msg = "Error Loading Registration: Check your entries and try again."; //+e.Message + " " + e.StackTrace;

                    CommunicationModel C = new CommunicationModel();
                    C.SendErrorEmail(e.Message + Environment.NewLine + "Student Name: " + FirstName + " " + LastName, "NewClassRegistration");

                    C.LogErrorToDB("NewClassRegistration", e.Message, e.StackTrace);

                }
            }
            return msg;
        }

		public void SendRegistrationEmil(long id) {

			CM.SendRegistrationMessage(id);
		}

        public Int32 VerifyClassOpenings(int COURSE_ID)
        {
            Int32 msg;
            msg = c.VerifyClassOpenings(COURSE_ID);
            return msg;
        }
        public string VerifyPromoCode(string code)
        {
            string msg;

            msg = GM.VerifyPromoCode(code);

            return msg;
        }

        public string ConfirmClassRegistration(Int64 RECEIPT)
        {
            string result = "";

            try
            {
                result = c.RegistrationConfirm(RECEIPT);
            }
            catch
            {
                result = "Fail";
            }

            return result;
        }
        public string AddressValidation(string a, string c, string s, string z)
        {
            XmlDocument r = new XmlDocument();

            // Query the USPS Address API
            r = AV.ValidateAddress(a,c,s, z);

            // Return the XML response
            return r.InnerXml;
        }
    }
}

vMTS/Views/Home/Index.cshtml
@model vMTS.Models.GeneralModel

@{var itemList = @Model.GetCarouselImages.ToList();}
<p class="lead navbar-center">Welcome To vMTS...Learn to Ride at Aladdin Temp-Rite, Hendersonville, Tennessee</p>
@if (itemList.Count() >= 1)
{
    var n = 0;
    var active = "active";

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ol class="carousel-indicators">
            @foreach (var i in itemList)
            {
                if (n == 0) { active = "active"; } else { active = ""; }
                <li data-target="#carousel-example-generic" data-slide-to="@n" class="@active"></li>
                n = n + 1;
            }
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            @* SET n BACK TO ZERO *@
            @{n = 0;}
            @foreach (var i in itemList)
            {
                if (n == 0) { active = "item active"; } else { active = "item"; }

                <div class="@active">
                    <img class="img-responsive center-block" src="~/images/carousel/@i.ImgName" height="150" alt="@i.ImgCaption">
                    <div class="carousel-caption">
                        <h5>@i.ImgCaption</h5>
                    </div>
                </div>
                
                n = n + 1;
            }
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
}
<hr />
<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Successful Completion Includes</h3>
    </div>
    <div class="panel-body">
        <ul class="list-unstyled lead">
            <li>Completion of all exercises</li>
            <li>Completion of the written exam (may be given orally)</li>
            <li>Completion of the skills riding evaluation</li>
        </ul>
        <p class="lead text-warning">Registration and attendance will not automatically guarantee successful completion</p>
        <p class="text-left">
            @Html.ActionLink("Register Now", "index", "registration", null, new { @class = "btn btn-info" })
        </p>
    </div>
</div>
<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Licensing</h3>
    </div>
    <div class="panel-body">
        <p class="lead">Successful completion of the Basic RiderCourse or the Experienced RiderCourse may waive the written and riding portions of the Tennessee Department of MotorVehicles licensing test.</p>
        <p class="lead">Most insurance companies offer a 10% discount on motorcycle insurance for successful completion of this course.</p>
        @*<p><a class="btn btn-info" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>*@
    </div>
</div>
<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Motorcycle Education</h3>
    </div>
    <div class="panel-body">
        <p class="lead">Through different levels of motorcycle training and education programs offered by Volunteer Motorcycle Training Services, participants can experience motorcycling or improve their riding skills.</p>
        <p>The courses are presented in cooperation with the Tennessee Motorcycle Rider Education Program (TNMREP) and the Motorcycle Safety Foundation (MSF).</p>
        <p><a class="btn btn-info" href="http://www.msf-usa.org/" target="_blank">Learn more &raquo;</a></p>
    </div>
</div>
@*<div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
</div>*@

vMTS/Views/Home/_location.cshtml
<div class="panel panel-info">
    <div class="panel-heading"><h3 class="panel-title">Directions to Course Site</h3></div>
    <div class="panel-body">
        <a class="text-left" href="http://aladdintemprite.com/" target="_blank"><img class="img-responsive" src="~/images/SponsorLogo/Aladdin_logo.jpg" /></a>
        <p class="lead">
            Aladdin Temp-Rite is located on the east side of Hendersonville, north side of Main Street (also known as Gallatin Pike or highway 31E) between traffic light 10 and traffic light 11. The manufacturing plant is located behind NTB and Office Depot, across the highway from Burger King and Regions Bank.
            <br />
            The class room and riding range is located in the east parking lot of Aladdin Temp Rite.
            <br />
            <strong>Entrance to vMTS is the shipping/receiving lane next to Pinnacle Bank.</strong>
        </p>
        <a href="http://mapq.st/1TviDGr" target="_blank">Get directions (Mapquest)</a> 
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading"><h3 class="panel-title">Course Location Map</h3></div>
    <div class="panel-body">
        <div class="embed-responsive embed-responsive-4by3">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3215.088146724157!2d-86.60301177749135!3d36.31016923887458!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88644737790a3b17%3A0xf89f0d7f0e5e49f6!2s250+E+Main+St%2C+Hendersonville%2C+TN+37075!5e0!3m2!1sen!2sus!4v1449072458131" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
    <div class="pane-footer">
        <address>
            <p class="lead text-success">
                Aladdin Temp-Rite (Shipping and Receiving)<br />
                250 E Main St.<br />
                Hendersonville, TN 37075
            </p>
        </address>
    </div>
</div>

vMTS/Views/Home/_media.cshtml
<div class="panel panel-success">
    <div class="panel-heading"><h3 class="panel-title">Media</h3></div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/wzN4Y-C0tL8"></iframe>
                </div>
            </div>
            <div class="col-md-6">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ekkUzhh9E9A"></iframe>
                </div>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-6">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/XHo6kZc33Ks"></iframe>
                </div>
            </div>
            <div class="col-md-6">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/bWoKUPlJ214"></iframe>
                </div>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-6">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/lmeP6QWQhVo"></iframe>
                </div>
            </div>
            @*<div class="col-md-6">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/bWoKUPlJ214"></iframe>
                    </div>
                </div>*@
        </div>
    </div>
    <div class="panel-footer">Click video to play</div>
</div>

vMTS/Views/Home/about.cshtml
<h2>@ViewBag.Message</h2>

@Html.Partial("_Location")

vMTS/Views/Home/contact.cshtml
@model vMTS.Models.Company

<h1>@ViewBag.title</h1>
<div class="panel panel-primary">
    <div class="panel-heading"><h3 class="panel-title">Support</h3></div>
    <div class="panel-body">
        <address class="lead">
            <strong>Program Director:</strong><br /><a href="mailto:{@Model.ProgramDirectorEmail}">@Model.ProgramDirector</a><br />
            <strong>Registration Director:</strong><br /><a href="mailto:{@Model.RegistrationDirectorEmail}">@Model.RegistrationDirector</a><br />
            
            <strong>Phone:</strong><br />
            <a href="tel:+1{@Model.Telephone}">@Model.Telephone</a>
        </address>
    </div>
</div>

<div class="panel panel-warning">
    <div class="panel-heading"><h3 class="panel-title">Please Note</h3></div>
    <div class="panel-body">
        <address class="lead text-warning">
            All phone registrations must be accompanied by credit card payment to guarantee a reservation.<br />
            NO REFUNDS will be made, except for cancellations received at least 14 business days in advance of the scheduled class date.
        </address>
    </div>
</div>

@{Html.RenderPartial("_Location");}

vMTS/Views/Home/courses.cshtml
@model IEnumerable < vMTS.Models.CourseDescriptions >

    <h2> @ViewBag.Message </h2>

@if (Model.ToList().Count > 0)
{
    foreach (var i in Model)
    {
        <div class="panel panel-info">
            <div class="panel-heading"><h3 class="panel-title">@i.CourseName</h3></div>
            <div class="panel-body">
                @if (i.Description.Count >= 1)
                {
                    foreach (var d in i.Description)
                    {
                        <p class="lead">@d</p>
                    }
                }
                <p class="lead">Requires a minumum of @i.MinRiders riders for class to be held.</p>
            </div>

            @if(i.Requirements.Count >= 1)
            {

            <div class="list-group">
                <div class="list-group-item active">Course Requirements</div>
                @foreach (var r in i.Requirements)
                {
                    <div class="list-group-item">@r</div>
                }
                </div>
            }
                <div class="panel-footer">
                    <p>@i.Evaluation</p>
                    <p><a class="btn btn-danger" href="/Registration/Index">Register Now &raquo;</a></p>
                </div>

            </div>

    }
}
else
{
    <div class="panel panel-info">
        <div class="panel-heading"><h3 class="panel-title">vMST Courses</h3></div>
        <div class="panel-body">
            <p class="lead">We offer the following courses:</p>
            <div class="list-group">
                <div class="list-group-item">Basic RiderCourse I</div>
                <div class="list-group-item">Basic RiderCourse II</div>
                <div class="list-group-item">Advanced RiderCourse</div>
                <div class="list-group-item">Three-Wheel Basic RiderCourse</div>
                <div class="list-group-item">Skills Practice and Improvement</div>
           </div>

            <p>Contact us for more information</p>
            </div>
    </div>

}

<div class="panel panel-info">
    <div class="panel-heading"><h3 class="panel-title">Helpful Hint</h3></div>
    <div class="panel-body">
        Since the courses are physically demanding, we suggest that you do not plan late evening events and get ample rest prior to each days activities. If you have a small cooler, bring snacks, lunch, soft drinks, and water to class. Be sure your boots are comfortable, broken in, and have adequate traction. Be alert to each day’s weather conditions and dress in layers as appropriate for comfort.
        <p>Check out your knowledge by clicking on this link: <a href="http://msf-usa.org/CourseReview/Questionframe.htm?pagename=RiderCourse%20Info" target="_blank">BRC Review</a>.</p>
    </div>
</div>

@{Html.RenderPartial("_media");}

vMTS/Views/Home/fees.cshtml
@model IEnumerable<vMTS.Models.CourseDescriptions>


<h1>@ViewBag.title</h1>
@if (Model.ToList().Count > 0)
{
    foreach (var i in Model)
    {
        decimal cost;
        if (i.Cost != "" && Decimal.TryParse(i.Cost, out cost))
        {
            <a href="~/Home/Courses" class="btn btn-info btn-lg btn-block">@i.CourseName @String.Format("{0:c}", cost)</a>
        }
        else
        {
            <a href="~/Home/Courses" class="btn btn-info btn-lg btn-block">@i.CourseName @i.Cost</a>
        }
    }
}
<div class="well">
    <p class="lead">
        Skills Evaluation and Knowledge Written Testing is not required to register and participate in one of the courses offered by Volunteer Motorcycle Training Services (VMTS). The Skills Evaluation and Knowledge Written Testing is separate and apart from the courses.
    </p>
    <p class="lead">
        However, for those who wish to be examined and successfully complete the Skills Evaluation and Knowledge Written Test, VMTS will issue a certificate that may presented at the Department of Motor Vehicles (DMV) where the motorcycle endorsement will be added to the driver's license. Choosing to be examined by VMTS does not guarantee successful completion. The student must demonstrate the skills taught during the course.
    </p>
    <p class="lead text-primary">
        For those who wish to come ride for additional practice and already have a motorcycle endorsement or have no desire to obtain a motorcycle endorsement, classroom and testing is optional.
    </p>
</div>

<div class="well well-lg">
    <h3 class="text-primary">For groups of four or more, call for special pricing.</h3>
    <p>If you have a promotion code you will receive the associated discount when your order is processed.</p>
    <p class="lead">
        You may register and pay @Html.ActionLink("online", "Index", "Registration").<br />
        Or you may pay by check or Money Orders payable to VMTS and mail to 124 Robinhood Circle, Hendersonville, TN  37075. However, you are not guaranteed a place in the class until full payment is collected.
    </p>

    <p class="lead">
        <strong>NO REFUNDS</strong> will be made, except for course cancellations made at least 14 days in advance of scheduled class date. Students who are unable to meet the minimum physical requirements in the opinion of the instructor, or students whose behavior pose a hazard to themselves and/or other students, will be asked to discontinue the riding portion of the class with <strong>NO REFUND GIVEN</strong>. They may stay to observe the remainder of the class but will not be certified for completion. Students must successfully complete the entire class (including the written and riding skills evaluation) to receive a completion certificate and card.
    </p>

</div>

vMTS/Views/Home/instructors.cshtml
@model IEnumerable<vMTS.Models.Instructors>

@Scripts.Render("~/bundles/instructors")


<h1>@ViewBag.title</h1>

<div class="well well-lg">
    <p class="lead">Rider Coaches for the program are all experienced motorcyclists. Each is certified nationally by MSF, and then by TNMREP.</p>
</div>

@if (Model.ToList().Count > 0)
{
    foreach (var i in Model)
    {
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">@i.Name @i.Title</h3>
            </div>
            <div class="panel-body">
                <!-- Bio image will go here -->
                <div class="panel panel-default pull-left">
                    <div class="panel-body">
                        @if (i.Photo != "")
                        {
                            <img src="~/images/Instructors/@i.Photo" alt="@i.Name" class="img-responsive img-thumbnail" width="199" height="175" />

                        }
                        else
                        {
                            <img src="~/images/Instructors/pictures-icon.png" alt="Photo" class="img-responsive img-thumbnail" width="199" height="175" />
                        }
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-body">
                        @if (i.Bio.Count >= 1)
                        {
                            foreach (var d in i.Bio)
                            {
                                <p class="lead">@d</p>
                            }
                        }
                        else
                        {
                            <p class="lead">Check back for more information on @i.Name</p>
                        }
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                @if (i.Email != "")
                {
                    <abbr title="Email @i.Name">E:</abbr> <a href="mailto:@i.Email?Subject=vMTS%20RiderCoach" target="_top">@i.Email</a>
                }
            </div>
        </div>
}
}
else
{
    <p class="lead">Check back later for instructor information.</p>
}

vMTS/Views/Home/sponsors.cshtml
@model IEnumerable<vMTS.Models.Sponsor>


<h1>@ViewBag.title</h1>

<div>
    <hr />
@if (Model.ToList().Count > 0)
        {
            foreach (var i in Model)
            {
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">@Html.DisplayFor(model => i.Name)</h3>
                    </div>
                    <div class="panel-body">
                        <p><a href="@Html.DisplayFor(model => i.WebSite)" target="_blank"><img class="img-responsive" src="~/images/SponsorLogo/@i.Logo" /></a></p>
                        @*<p><a href="@Html.DisplayFor(model => i.Web_Url)" target="_blank"><img class="img-responsive" src="@Html.DisplayFor(model => i.Logo)" /></a></p>*@
                        <p class="lead">Visit them online at <a href="@Html.DisplayFor(model => i.WebSite)" target="_blank">@Html.DisplayFor(model => i.WebSite)</a></p>
                    </div>
                </div>
            }
        }
else
{
    <p class="lead">Check back later for sponsor information.</p>
}
</div>