vMTS/Controllers/AdminScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vMTS.Models;

namespace vMTS.Controllers
{
    //[RequireHttps]
    //[SessionExpire]
    //[RoleName]
    public class AdminScheduleController : Controller
    {
        AdministrationModel am = new AdministrationModel();
        ClassAdministration ca = new ClassAdministration();
        CommunicationModel com = new CommunicationModel();
        
        // GET: AdminSchedule
        public ActionResult Index()
        {
            ca.ClassType = ca.Get_ClassType("Basic Rider Course I");
            ca.CourseLocation = ca.Get_CourseLocation("Aladdin Temp-Rite");
            ca.CourseNumber = ca.Get_CourseNumber(1);
            ca.StartClassTimes = ca.Get_ClassTimes("07:00:00");
            ca.EndClassTimes = ca.Get_ClassTimes("19:00:00");
            
            ca.CurrentSchedule = am.GetSchedule();

            return View(ca);
        }
        public ActionResult _Schedule()
        {

            return View(am.GetSchedule());
        }

       public ActionResult _AddSchedule()
        {

            return View(ca);
        }

        public ActionResult _EditSchedule(Int32 id)
        {

            var list = new List<Class_Schedule_view>();
            list = ca.GetSchedule_edit(id);

            ca.EditSchedule = list;
            ca.ClassType = ca.Get_ClassType(list[0].CLASS_TYPE);
            ca.CourseLocation = ca.Get_CourseLocation(list[0].CLASS_LOCATION);
            ca.CourseNumber = ca.Get_CourseNumber(Convert.ToInt32(list[0].COURSE_NUMBER));
            ca.StartClassTimes = ca.Get_ClassTimes(list[0].ST_SELECTED.ToString());
            ca.EndClassTimes = ca.Get_ClassTimes(list[0].ET_SELECTED.ToString());

            return PartialView(ca);
        }
        public ActionResult _DeleteClass(Int32 id)
        {

            var list = new List<Class_Schedule_view>();
            list = ca.GetSchedule_edit(id);

            ca.EditSchedule = list;
            ca.ClassType = ca.Get_ClassType(list[0].CLASS_TYPE);
            ca.CourseLocation = ca.Get_CourseLocation(list[0].CLASS_LOCATION);
            ca.CourseNumber = ca.Get_CourseNumber(Convert.ToInt32(list[0].COURSE_NUMBER));
            //ca.StartClassTimes = ca.Get_ClassTimes(list[0].CLASS_START_TIME);
            //ca.EndClassTimes = ca.Get_ClassTimes(list[0].CLASS_END_TIME);

            return PartialView(ca);
        }
        public ActionResult _ClearSchedule()
        {
            try {
                string e = SignInManager.CurrentUser;
                string c = ca.GenerateCode();
                ViewBag.User = e;

                SendConfirmationCode(e, c);
            }
            catch
            {
                RedirectToAction("Login");
            }

            return PartialView();
        }
       public JsonResult ClassScheduleChanges(Int32 CLASS_ID, string CLASS_TYPE, string CLASS_START_DATE, string CLASS_START_TIME, string CLASS_END_DATE, string CLASS_END_TIME, string LOCATION, Int32 COURSE_NUMBER, Int32 OPEN_SEATS, Decimal CLASS_FEE)
        {
            var msg = "";

            msg = ca.ScheduleUpdates(CLASS_ID, CLASS_TYPE, CLASS_START_DATE, CLASS_START_TIME, CLASS_END_DATE, CLASS_END_TIME, LOCATION, COURSE_NUMBER, OPEN_SEATS, CLASS_FEE);

            return Json(msg);
        }

        public JsonResult CancelClass(Int32 CLASS_ID)
        {
            var msg = "";

            msg = ca.DeleteClass(CLASS_ID);

            return Json(msg);
        }

        public JsonResult SendConfirmationCode(string email, string code)
        {
            var msg = "";

            msg = com.SendConfirmationCode(email, code);

                Session["SchedCode"] = code;

            return Json(msg);
        }

        public JsonResult CheckConfirmationCode(string code)
        {
            var msg = "";
            bool match = ca.ReadTempCode(code);
            if (match) { msg = "Code Matched"; } else { msg = "No Match"; }

            return Json(msg);
        }

        public JsonResult ClearSchedule()
        {
            var msg = "";
                 ApplicationUser uc = new ApplicationUser();
                bool match = uc.ReadAdminTempContract(Session["SchedCode"].ToString());

                if (match)
                {
                    msg = ca.ClearSchedule();

                    Session.Remove("SchedCode");

                    //uc.RemoveAdminTempContract();
                }
                else
                {
                    msg = "Code did not match";
                }
            return Json(msg);
        }

    }
}

vMTS/Views/AdminSchedule/Index.cshtml
@model vMTS.Models.ClassAdministration

@{
    ViewBag.Title = "Schedule Administration";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h3>@ViewBag.Title</h3>
<div class="container-fluid">
    <div class="row">
        <div id="current_schedule" class="col-xs-12 col-sm-10 col-md-6">@Html.Partial("_schedule", Model)</div>
        <!-- Add New Class Widget -->
        <div class="col-xs-12 col-sm-10 col-md-6">@Html.Partial("_addschedule", Model)</div>
    </div>
</div>

vMTS/Views/AdminSchedule/_AddSchedule.cshtml
@model vMTS.Models.ClassAdministration

@{Layout = "";}
@*@Scripts.Render("~/bundles/admin_Class")*@

<div class="well">
    <h1>Add New Class</h1>
    @using (Html.BeginForm("", "", FormMethod.Post, new { id = "form_NewClass", @class = "form-horizontal" }))
    {
        @Html.Hidden("CLASS_ID", 0)
        <div class="form-group">
            <label class="sr-only">Class Type</label>
            @Html.DropDownList("CLASS_TYPE", Model.ClassType, "Class Type", new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label class="sr-only">Start Date</label>
            @Html.TextBox("CLASS_START_DATE", DateTime.Today, "{0:d}", new { @readonly = true, @class = "form-control" })
        </div>
        <div class="form-group">
            <label class="sr-only">Start Time</label>
            @Html.DropDownList("CLASS_START_TIME", Model.StartClassTimes, "Start Time", new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label class="sr-only">End Date</label>
            @Html.TextBox("CLASS_END_DATE", DateTime.Today, "{0:d}", new { @readonly = true, @class = "form-control" })
        </div>
        <div class="form-group">
            <label class="sr-only">End Time</label>
            @Html.DropDownList("CLASS_END_TIME", Model.EndClassTimes, "End Time", new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label class="sr-only">Class Location</label>
            @Html.DropDownList("LOCATION", Model.CourseLocation, "Location", new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label class="sr-only">Course Number</label>
            @Html.DropDownList("COURSE_NUMBER", Model.CourseNumber, "Course Number", new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label class="sr-only">Open Seats</label>
            @Html.TextBox("OPEN_SEATS", "11", new { @type = "number", @class = "form-control" })
        </div>
        <div class="form-group">
            <label class="sr-only">Class Fee</label>
            <div class="input-group">
                <span class="input-group-addon">$</span>
                @Html.TextBox("CLASS_FEE", "195.00", "{0:0.00}", new { maxlength = "6", @class = "form-control" })
            </div>
        </div>
        @*<div class="form-group">
            <label class="sr-only">Class Description</label>
            @Html.TextArea("CLASS_DESCRIPTION", "The Basic RiderCourse is designed to teach the novice motorcyclist the skills necessary to ride safely on the street. The course takes the beginning rider through the basics of motorcycle operation: straight line riding, turning, shifting, stopping and safe riding strategies. A minimum of 4 riders required to hold class.", new { @rows = "5", @cols = "10", @class = "form-control", @placeholder="Class Description" })
        </div>*@
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-sm">Save</button>
        </div>
    }
</div>

vMTS/Views/AdminSchedule/_ClearSchedule.cshtml
@{Layout = "";}
@Scripts.Render("~/bundles/admin_Class")

<h2>Clear the Current Schedule</h2>
<h3>A confirmation code has been sent to <strong>@ViewBag.User</strong></h3>
<div class="well">
    @using (Html.BeginForm("", "", FormMethod.Post, new { id = "form_Confirmation", @class = "form-horizontal" }))
    {
        <div class="form-group">
            <label class="lead">Confirmation Code</label>
            <div class="input-group">
                <span class="input-group-addon glyphicon glyphicon-thumbs-up"></span>
                @Html.TextBox("code","", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-sm" data-trigger="hover" data-container="body" data-toggle="popover" data-placement="right" data-content="This will clear the current schedule." data-original-title="" title="Clear Current Schedule">Confirm Now</button>
        </div>

    }
    </div>

<div id="ClearScheduleAction" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Clear Current Schedule</h4>
            </div>
            <div class="modal-body">
                <div id="before">
                    <h1>Are you sure you want to clear the schedule?</h1>
                    <p class="lead">This will clear all entries from the current schedule.</p>
                </div>
                <div id="after" aria-hidden="true">
                    <p id="text" class="lead"></p>
                </div>
            </div>
            <div class="modal-footer">
                <div id="before_footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button id="form_ClearSchedule" type="button" class="btn btn-primary">Submit</button>
                </div>
                <div id="after_footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

vMTS/Views/AdminSchedule/_DeleteClass.cshtml
@model vMTS.Models.ClassAdministration

@{var detail = Model.EditSchedule.ToList();}

@{Layout = "";}
@Scripts.Render("~/bundles/admin_Class")

<div class="well">
    @if (detail.Count <= 0)
    {
        <p class="lead">Oops...we couldn't find any details about this class!</p>
    }
    else
    {
        foreach (var i in detail)
        {
            <div class="form-group">
                <label>Class Day</label>
                @Html.DisplayFor(v => i.ClassDay, new { maxlength = "30", @class = "form-control", value = @i.ClassDay })
            </div>
            <div class="form-group">
                <label>Class Type</label>
                @Html.DropDownList("CLASS_TYPE", Model.ClassType, "Select", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Start Date</label>
                @Html.TextBoxFor(v => i.CLASS_START_DATE, "{0:d}", new { @readonly = true, @class = "form-control", value = @i.CLASS_START_DATE })
            </div>
            <div class="form-group">
                <label>End Date</label>
                @Html.TextBoxFor(v => i.CLASS_END_DATE, "{0:d}", new { @readonly = true, @class = "form-control", value = @i.CLASS_END_DATE })
            </div>
            <div class="form-group">
                <label>Open Seats</label>
                @Html.TextBoxFor(v => i.OPEN_SEATS, new { @type = "number", @class = "form-control", value = @i.OPEN_SEATS })
            </div>
            <div class="form-group">
                <label>Class Location</label>
                @Html.DropDownList("LOCATION", Model.CourseLocation, "Select", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Course Number</label>
                @Html.DropDownList("COURSE_NUMBER", Model.CourseNumber, "Select", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Class Fee</label>
                <div class="input-group">
                    <span class="input-group-addon">$</span>
                    @Html.TextBoxFor(v => i.CLASS_FEE, "{0:0.00}", new { maxlength = "6", @class = "form-control", value = @i.CLASS_FEE })
                </div>
            </div>
            using (Html.BeginForm("", "", FormMethod.Post, new { id = "form_DeleteClass", @class = "form-horizontal" }))
            {
                @Html.Hidden("CLASS_ID", i.CLASS_ID)

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-sm">Save Changes</button>
                </div>
            }
        }
    }
</div>

vMTS/Views/AdminSchedule/_EditSchedule.cshtml
@model vMTS.Models.ClassAdministration

@{var detail = Model.EditSchedule.ToList();}

@{Layout = "";}
@Scripts.Render("~/bundles/admin_Class")

<div class="well">
    @if (detail.Count <= 0)
    {
        <p class="lead">Oops...we couldn't find any details about this class!</p>
    }
    else
    {
        using (Html.BeginForm("", "", FormMethod.Post, new { id = "form_EditClass", @class = "form-horizontal" }))
        {
            foreach (var i in detail)
            {
                @Html.Hidden("CLASS_ID", i.CLASS_ID)
                <div class="form-group">
                    <label>Class Day</label>
                    @Html.DisplayFor(v => i.ClassDay, new { maxlength = "30", @class = "form-control", value = @i.ClassDay })
                </div>
                <div class="form-group">
                    <label>Class Type</label>
                    @Html.DropDownList("CLASS_TYPE", Model.ClassType, "Select", new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Start Date</label>
                    @Html.TextBox("CLASS_START_DATE",i.CLASS_START_DATE, "{0:d}", new { @readonly = true, @class = "form-control"  })
                </div>
                <div class="form-group">
                    <label>Start Time</label>
                    @Html.DropDownList("CLASS_START_TIME", Model.StartClassTimes, "Select", new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>End Date</label>
                    @Html.TextBox("CLASS_END_DATE",i.CLASS_END_DATE, "{0:d}", new { @readonly = true, @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>End Time</label>
                    @Html.DropDownList("CLASS_END_TIME", Model.EndClassTimes, "Select", new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Open Seats</label>
                    @Html.TextBox("OPEN_SEATS",i.OPEN_SEATS, new { @type = "number", @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Class Location</label>
                    @Html.DropDownList("LOCATION", Model.CourseLocation, "Select", new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Course Number</label>
                    @Html.DropDownList("COURSE_NUMBER", Model.CourseNumber, "Select", new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Class Fee</label>
                    <div class="input-group">
                        <span class="input-group-addon">$</span>
                        @Html.TextBox("CLASS_FEE",i.CLASS_FEE, "{0:0.00}", new { maxlength = "6", @class = "form-control" })
                    </div>
                </div>
                @*<div class="form-group">
                    <label>Class Description</label>
                    @Html.TextArea("CLASS_DESCRIPTION", i.CLASS_DESCRIPTION, new { @class = "form-control", @rows = "10", @cols = "100" })
                </div>*@

            }
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-sm">Save Changes</button>
            </div>
        }
    }
</div>

vMTS/Views/AdminSchedule/_Schedule.cshtml
@model vMTS.Models.ClassAdministration

@{var itemList = @Model.CurrentSchedule.ToList();}


@{Layout = "";}
@Scripts.Render("~/bundles/admin_Class")

<div class="panel panel-default">
    <div class="panel-body">
@if (itemList.Count > 0)
{

    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th>Class Day</th>
                <th>Openings</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var i in itemList)
            {
                <tr>
                    <td>@i.ClassDay</td>
                    <td>@i.OPEN_SEATS</td>
                    <td id="classnum">
                        @Html.ActionLink("Edit", "_EditSchedule", "AdminSchedule", new { id = @i.CLASS_ID }, new { @class = "btn btn-info btn-xs", @title="Edit Class" })&nbsp;
                        @Html.ActionLink("Cancel", "_DeleteClass", "AdminSchedule", new { id = @i.CLASS_ID }, new { @class = "btn btn-info btn-xs", @title="Cancel Class" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}    </div>
</div>

<div class="modal fade bs-modal-lg" id="bs-modal-lg" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal_title"></h4>
            </div>
            <div id="Schedule" class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer">
                <div id="alertText" class="navbar-left alert alert-danger hidden" role="alert">...</div>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@*<div id="ScheduleAlert" class="modal bs-modal-sm">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <p class="lead"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>*@